apiVersion: v1
kind: Service
metadata:
  labels:
    app: springio-demo
  name: springio-demo
  namespace: hellospace
spec:
  selector:
    app: springio-demo
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080